
debug_mode: True

# visible video precentage
video_per: .3
num_latents: 256
dataset:  UCF-101
precision: mixed
data_dir: /kaggle/working/Khoa-luan-tot-nghiep/data/UCF-101_mine/
label_dir: /kaggle/working/Khoa-luan-tot-nghiep/labels/UCF-101_mine/

# GPU-device related parser arguments & number of workers
workers: 2

# set batch size
batch_size: 32
frame_size: 224
